apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
  namespace: garmento
spec:
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec:
      containers:
        - name: service-registry
          image: garmento.io/service-registry:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "250m"
          ports:
            - containerPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
  namespace: garmento
spec:
  selector:
    app: service-registry
  type: ClusterIP
  clusterIP: 10.96.3.0
  ports:
  - name: rest-api
    port: 443
    protocol: TCP
    targetPort: 8761

