"""init job table

Revision ID: 2c8d19073453
Revises: 
Create Date: 2024-03-17 22:25:23.512311

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c8d19073453'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inference_jobs',
    sa.Column('id', sa.String(length=48), nullable=False),
    sa.Column('status', sa.String(length=48), nullable=False),
    sa.Column('result_image_id', sa.String(length=48), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inference_jobs')
    # ### end Alembic commands ###
